.OPTIMIZE

COS = nt
LOS = nt
BIN = e:\bin\

APFLAG = -dXTC68 -dDOS_LIKE
CFLAGS = -j -w4 -e25 -zp4 -zq -oneatx -5 -bt=$(COS)
LDFLAGS = SYS $(LOS) op st=20000 op maxe=25 op q

SD = ..\

CC = wcc386
LD = wlink

#
OBJS =   ld.obj

.c:    $(SD)
.c.obj :
    $(cc) $[* $(CFLAGS) $(APFLAG)

all:    $(BIN)ld.exe

ld.obj : $(SD)ld.c

$(BIN)ld.exe:    $(OBJS)
    $(ld) $(ldflags)  name $(BIN)qld.exe file ld.obj





